channels:
  - conda-forge
  - bioconda
  - agbiome
dependencies:
  - bioconda::snakemake-minimal =5.4.5
  - fastqc =0.11.9
  - multiqc =1.8
  - bbtools =37.62
  - samtools =1.10
  - star =2.7.3a
  - subread =2.0.0
